DROP TABLE IF EXISTS courses;

CREATE TABLE courses (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	nickname VARCHAR(255) NOT NULL,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);
